Pkg.update()

# Install required Julia packages
Pkg.add("SpecialFunctions")
Pkg.add("FastGaussQuadrature")
Pkg.add("GSL")
Pkg.add("IterativeSolvers")
Pkg.add("LinearMaps")
Pkg.add("PyPlot")
Pkg.add("SymPy")
Pkg.add("PyCall")
Pkg.add("LowRankApprox")
Pkg.add("MATLAB")
Pkg.add("NullableArrays")
Pkg.add("Revise")
Pkg.add("FMMLIB2D")
Pkg.add("FINUFFT")
Pkg.add("LaTeXStrings")
Pkg.add("JLD")
Pkg.add("Glob")
Pkg.add("HDF5")
Pkg.add("FileIO")
Pkg.add("Humanize")
Pkg.add("Interpolations")
